### ISSUE TITLE
maf_to_bed.py error

### ISSUE THREAD

**Issue by yuzhenpeng** [henryjuho/WGAbed#12]
Dear author,
First, thank for your wonderful scripts.
But, when I used the maf_to_bed.py. I got an error.
`$maf_to_bed.py -i all.chr5.maf.gz -r hg38 -c 5
grep: write error

gzip: stdout: Broken pipe
Traceback (most recent call last):
  File "/Bio/home/Yanglab/Yuzhenpeng/opt/softwares/WGAbed/maf_to_bed.py", line 227, in <module>
    main()
  File "/Bio/home/Yanglab/Yuzhenpeng/opt/softwares/WGAbed/maf_to_bed.py", line 195, in main
    align_score = line.split()[1].split('=')[1]
IndexError: list index out of range
`

Could you help me. Thanks. @henryjuho

**Comment by henryjuho** [comment]
Hi, sorry for the slow reply. I believe this is due to the way alignment scores are coded in your files. I noticed that your fork of the repo is actually a few commits behind the main one, and is lacking a commit that may fix this for you. I'd suggest you update your fork and see if the problem still persists.

Henry

**Comment by yuzhenpeng** [comment]
Ok. Thanks for your kind help. I will try it.

zhenpeng

**Comment by yuzhenpeng** [comment]
Dear Henry,

I am sorry for disturbing.

I now have one question. 

I have a MAF file, which contains six species mutiple genome alignment, like human-mouse-dog-cattle-dolphin-killer whale. I wonder how to find the dolphin-killer whale specific mutations (insertion or deletion) form MAF. 

Could you give me some help.

Thank you.

zhengpeng

**Comment by henryjuho** [comment]
Hi. 

I would convert your maf file to a wga.bed file and then use the 'wga_bed_indels.py' script to return all the insertions and deletions in the alignment. I would then loop through the resulting file line by line in python (or your preferred language) and identify sites where the dolphin and killer whale carry an insertion or deletion that is not present in the out-groups. 

It might also be worth your time checking out Biopython's AlignIO (https://biopython.org/wiki/AlignIO) which seems to accept MAF files these days.

Hope that helps. Henry

**Comment by yuzhenpeng** [comment]
Thans for your rapidly response. 

I only find the "max_length" parameter in 'wga_bed_indels.py'.
May I set the min_length of indels.

**Comment by henryjuho** [comment]
Hi. There is no minimum length option in that script, but if you are looping through the output to identify INDELs specific to the dolphin and killer whale anyway then filtering by INDEL length at the same time should be relatively straight forward.
